### ISSUE TITLE
Linear interpolation

### ISSUE THREAD

**Issue by Kn3cht** [DominikButz/SwiftUIGraphs#2]
Hi, 
is there any way to replace the quad curve with linear interpolation?

Thx in advance

**Comment by DominikButz** [comment]
Hi, please update to version 0.7.2. In the DYLineChart initialiser, add the property interpolationType in the DYLineChartSettings and set it to linear. That should do the trick.

**Comment by Kn3cht** [comment]
Hi, thx for the fast reply.
For my use case I'd also need optional text annotations above the points + vertical lines from each point down to the x-Axis (similar to the grid lines).
These features are not implemented yet right?

**Comment by DominikButz** [comment]
Thanks for the proposal, I will look into it.

**Comment by DominikButz** [comment]
Please check out version 0.8. 
Adding additional grid lines from each data point looks a bit messy if you have many data points. You can check out the show..AxisDataPointLines properties of the xAxis and yAxis settings. 
<img width="643" alt="Screenshot 2022-07-18 at 14 20 11" src="https://user-images.githubusercontent.com/5699871/179457672-14ea2189-fded-493d-a1f1-16ac928b50d5.png">

I personally prefer this solution (show..AxisSelectedDataPointLine property in both axis settings structs) - the line to the x- and/or y-axis only shows for the selected data point:
<img width="650" alt="Screenshot 2022-07-18 at 14 18 41" src="https://user-images.githubusercontent.com/5699871/179457676-b883ad7a-b604-469b-a4ee-5bd5468e8495.png">

**Comment by Kn3cht** [comment]
Unfortunately I cannot see v0.8 yet. 
But the feature looks very promising for my use case as I'm not dealing with many points

**Comment by DominikButz** [comment]
Ok - have you tried refreshing the page in your browser? 
<img width="593" alt="Screenshot 2022-07-18 at 16 35 52" src="https://user-images.githubusercontent.com/5699871/179474245-198281db-a50d-4060-8e7e-b59844f453c9.png">

**Comment by Kn3cht** [comment]
Browser caching worked too well 😅

**Comment by DominikButz** [comment]
Closed after update to v0.8
