### ISSUE TITLE
Line on graph sometimes do not appear, when DYLineChart is used inside of TabView.

### ISSUE THREAD

**Issue by SAleksiev** [DominikButz/SwiftUIGraphs#3]
I am currently using the DYLineChartView inside of a TabView and sometimes when I am navigating from one view to another I face three different situations in the Chart:

- The animation appears and works fine
- The animation does not appear and the lines are static
- The lines are missing

The initializer of DYLineChartView:
`
DYLineChartView(dataPoints: viewModel.dataPoints(for: .regular, for: aggregatedData),
                        selectedIndex: $selectedDataIndex,
                        xValueConverter: { (xValue) -> String in
            return Date(timeIntervalSinceReferenceDate: xValue).toString(format: Constants.xValueFormat).uppercased()
        }, yValueConverter: { (yValue) -> String in
            guard yValue == 0.0 else {
                return NumberFormatter().format(with: .decimal).string(from: yValue) ?? ""
            }
            return "%"
        }, chartFrameHeight: 100,
                        settings: DYLineChartSettings(lineColor: .black,
                                                      lineAnimationDuration: 0.35,
                                                      gradient: LinearGradient(gradient: Gradient(colors: [.clear, .clear]),
                                                                               startPoint: .top,
                                                                               endPoint: .bottom),
                                                      pointDiameter: 10,
                                                      pointColor: .black,
                                                      pointBackgroundColor: .white,
                                                      selectorLineColor: .clear,
                                                      selectorLinePointColor: .clear,
                                                      interpolationType: .linear,
                                                      yAxisSettings: YAxisSettings(showYAxis: true,
                                                                                   yAxisPosition: .leading,
                                                                                   yAxisViewWidth: 40,
                                                                                   yAxisGridLineStrokeStyle: .init(lineWidth: 1,
                                                                                                                   lineCap: CGLineCap.butt,
                                                                                                                   lineJoin: CGLineJoin.bevel,
                                                                                                                   miterLimit: 1,
                                                                                                                   dash: [1],
                                                                                                                   dashPhase: 1),
                                                                                   yAxisFontSize: 8,
                                                                                   yAxisMinMaxOverride: (min: 0.0, max: 100),
                                                                                   yAxisIntervalOverride: 25),
                                                      xAxisSettings: DYLineChartXAxisSettings(showXAxis: true,
                                                                                              showXAxisGridLines: false,
                                                                                              xAxisInterval: 1350000,
                                                                                              xAxisFontSize: 8)))
`

Example of data-points used:
`
{
            "date": "2022-06-27",
            "completionRate": 1,
            "mood": 3
        },
        {
            "date": "2022-07-04",
            "completionRate": 0.9166666666666666
        },
        {
            "date": "2022-07-11",
            "completionRate": 0.9166666666666666
        },
        {
            "date": "2022-07-18",
            "completionRate": 0.9230769230769231
        },
        {
            "date": "2022-07-25",
            "completionRate": 0.9166666666666666
        },
        {
            "date": "2022-08-01",
            "completionRate": 0
        },
        {
            "date": "2022-08-08",
            "completionRate": 0
        },
        {
            "date": "2022-08-15",
            "completionRate": 0.2
        }
`

**Comment by DominikButz** [comment]
Thanks - I will look into it - I should be able to give a feedback by tomorrow.

**Comment by DominikButz** [comment]
I have created a new branch called animationAppearIssue. In that branch I have not changed anything in the source files - I have only amended the example by adding "Tabbed Line Charts" to the menu. You will see that you can swipe horizontally and different versions of the line chart appear (each in a different colour)- there are only 3 in total. The DYDataPoint values of the data points are different for each tab. Check out the file "TabbedLineCharts" in the example folder. 
So far I can't reproduce the issue of the line not appearing at all. It is true that there is no animation any more once the tab has appeared before. However, I don't really see this as a big issue... 
I suggest the following: make changes to the example (but not to the package source files) to bring it closer to your original code - the goal is to bring the example closer to your project configuration so that the conditions that lead to the issue of the line not appearing at all can be reproduced. Under the conditions of my app that I created SwiftUI Graphs for, all is working fine so far.

**Comment by DominikButz** [comment]
update: added lineEnd print statement in showChartContent function.

**Comment by SAleksiev** [comment]
Thanks, I will take a look and come back to you as soon as possible.

The difference between your project and the one I am working is mainly related that I make API requests and refreshing the whole View, while in your case you got predefined data for each tab.

**Comment by SAleksiev** [comment]
When I swipe to an "event" that does not have data so far, I do make a specific request, get the data points and show the DYLineChartView.

Sometimes I can see 4 prints of lineEnd. Sometimes I see 5.
All of those prints show:
line end 0.0

If I swipe back I can see only one print which shows:
line end 1.0

Sometimes the console also logs, instead of showing line end value:
boringssl_metrics_log_metric_block_invoke(153) Failed to log metrics

**Comment by SAleksiev** [comment]
Also, the function line():
Trims:
trim(from: 0, to: self.settings.showAppearAnimation ? self.lineEnd : 1)

so in that case if self.lineEnd is equal to 0, then the trim starts from 0 and it ends to 0.

I guess that's the issue.

**Comment by DominikButz** [comment]
Yes, this is how a line animation works - the endLine value is set to 1 in a withAnimation closure in the onAppear modifier. 
I have made a new commit on the animationFix branch. endLine does not exist any more now and I have deleted the trim modifier. The animation now only depends on the showLine state variable. The animation is achieved in the same way as the segmented line - by applying a mask. Please check if it fixes this issue.

**Comment by SAleksiev** [comment]
Hey Dominik, I do have the same issue after using the animationAppearIssue branch. Also, opening the line() function, does not seems changed. The trim function is still used as well as I can still use the lineEnd. Did you push your changes?

**Comment by DominikButz** [comment]
sorry, you're right - just pushed the new commit.

**Comment by DominikButz** [comment]
Stale, issue closed
